// Copyright © 2026 Randy Wilson. All rights reserved.
//
// Regenerated by Scripts/make_app.sh on every build — edit that script, not this file.
// The minor version is bumped per build so the About box tells you whether the app in
// the Dock is the one you just built.

import Foundation

public enum BuildInfo {
    public static let version = "1.7"
    public static let buildDate = "2026-09-21 at 1:55 PM"
}
