#!/bin/bash
# Copyright © 2026 Randy Wilson. All rights reserved.
#
# Wraps the Swift Package executable in a real BlogComposer.app, so it has a
# Dock icon, a Finder icon and a proper application menu without `swift run`.
#
#   ./Scripts/make_app.sh              build to ./build/BlogComposer.app
#   ./Scripts/make_app.sh --install    also copy it into ~/Applications
#   ./Scripts/make_app.sh --debug      bundle the debug build instead
#   ./Scripts/make_app.sh --universal  build arm64 + x86_64, to run on Intel Macs too

set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"

APP_NAME="BlogComposer"
BUNDLE_ID="com.randywilson.blogcomposer"
MIN_MACOS="14.0"
BUILD_INFO="$ROOT/Sources/BlogComposerCore/BuildInfo.swift"

CONFIG="release"
INSTALL=0
BUILD_ARGS=()
for arg in "$@"; do
    case "$arg" in
        --install)   INSTALL=1 ;;
        --debug)     CONFIG="debug" ;;
        --universal) BUILD_ARGS+=(--arch arm64 --arch x86_64) ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

# The Xcode toolchain refuses to run until its licence is accepted, which needs
# an admin account. The Command Line Tools carry their own, already-accepted
# licence, so fall back to them rather than failing.
if ! xcrun --find swift >/dev/null 2>&1; then
    export DEVELOPER_DIR=/Library/Developer/CommandLineTools
    echo "note: using the Command Line Tools toolchain (Xcode licence not accepted)"
fi

# Bump the minor version and stamp the build time, so the About box identifies
# exactly which build is running — the Dock launches build/BlogComposer.app, and
# "Version 1.0" on every build made it impossible to tell old from new.
# Written before the compile so the constants land in the binary.
CURRENT="$(sed -n 's/.*static let version = "\([0-9][0-9.]*\)".*/\1/p' "$BUILD_INFO" 2>/dev/null || true)"
[ -n "$CURRENT" ] || CURRENT="1.0"
VERSION="${CURRENT%%.*}.$(( ${CURRENT##*.} + 1 ))"
BUILD_STAMP="$(date '+%Y-%m-%d at %-I:%M %p')"

echo "==> Version $CURRENT -> $VERSION  (built $BUILD_STAMP)"
cat > "$BUILD_INFO" <<SWIFT
// Copyright © 2026 Randy Wilson. All rights reserved.
//
// Regenerated by Scripts/make_app.sh on every build — edit that script, not this file.
// The minor version is bumped per build so the About box tells you whether the app in
// the Dock is the one you just built.

import Foundation

public enum BuildInfo {
    public static let version = "$VERSION"
    public static let buildDate = "$BUILD_STAMP"
}
SWIFT

echo "==> Building ($CONFIG)"
swift build -c "$CONFIG" ${BUILD_ARGS+"${BUILD_ARGS[@]}"}
# A universal build lands somewhere else, so ask rather than assume.
BIN_DIR="$(swift build -c "$CONFIG" ${BUILD_ARGS+"${BUILD_ARGS[@]}"} --show-bin-path)"

echo "==> Refreshing the icon"
swift Tools/MakeAppIcon.swift >/dev/null

APP="$ROOT/build/$APP_NAME.app"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

echo "==> Assembling $APP"
cp "$BIN_DIR/$APP_NAME" "$APP/Contents/MacOS/$APP_NAME"
cp "$ROOT/Icons/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"

# Bundle.module looks for the package's resource bundles beside the executable
# or in the main bundle's Resources, so blog.css and AppIcon.png must come too.
for bundle in "$BIN_DIR"/*.bundle; do
    [ -e "$bundle" ] || continue
    # A universal build also leaves the test bundle here; don't ship fixtures.
    case "$(basename "$bundle")" in *Tests.bundle) continue ;; esac
    cp -R "$bundle" "$APP/Contents/Resources/"
done

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>          <string>en</string>
    <key>CFBundleExecutable</key>                 <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>                 <string>$BUNDLE_ID</string>
    <key>CFBundleInfoDictionaryVersion</key>      <string>6.0</string>
    <key>CFBundleName</key>                       <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>                <string>Blog Composer</string>
    <key>CFBundleIconFile</key>                   <string>AppIcon</string>
    <key>CFBundlePackageType</key>                <string>APPL</string>
    <key>CFBundleShortVersionString</key>         <string>$VERSION</string>
    <key>CFBundleVersion</key>                    <string>$VERSION</string>
    <key>LSMinimumSystemVersion</key>             <string>$MIN_MACOS</string>
    <key>LSApplicationCategoryType</key>          <string>public.app-category.productivity</string>
    <key>NSHighResolutionCapable</key>            <true/>
    <key>NSPrincipalClass</key>                   <string>NSApplication</string>
    <key>NSHumanReadableCopyright</key>           <string>Copyright © 2026 Randy Wilson. All rights reserved.</string>
</dict>
</plist>
PLIST

# Sign with a real certificate when one exists, otherwise ad-hoc. This matters
# more than it looks: an ad-hoc signature is identified purely by content hash,
# so every rebuild is a different app to macOS and the keychain and TCC prompt
# again. A certificate makes the designated requirement the bundle id plus the
# cert, which survives rebuilds.
#
# Override with:  SIGN_IDENTITY="Some Identity" ./Scripts/make_app.sh
pick_identity() {
    local available preferred name
    available=$(security find-identity -v -p codesigning 2>/dev/null) || return 0
    for preferred in "Developer ID Application" "Apple Development" "Mac Developer"; do
        name=$(printf '%s\n' "$available" \
               | sed -n "s/.*\"\($preferred[^\"]*\)\".*/\1/p" | head -1)
        if [ -n "$name" ]; then printf '%s' "$name"; return 0; fi
    done
    # Anything else valid for code signing, e.g. a self-signed local certificate.
    printf '%s\n' "$available" \
        | sed -n 's/.*[0-9])[[:space:]]*[0-9A-F]\{40\}[[:space:]]*"\([^"]*\)".*/\1/p' | head -1
}

SIGN_IDENTITY="${SIGN_IDENTITY:-$(pick_identity)}"
if [ -n "$SIGN_IDENTITY" ]; then
    echo "==> Signing as: $SIGN_IDENTITY"
    SIGN_ARGS=(--force --sign "$SIGN_IDENTITY" --identifier "$BUNDLE_ID")
    # The hardened runtime is required for notarisation but restricts the
    # process, so only impose it on the identity that could be notarised.
    case "$SIGN_IDENTITY" in
        "Developer ID Application"*) SIGN_ARGS+=(--options runtime --timestamp) ;;
    esac
    codesign "${SIGN_ARGS[@]}" "$APP"
else
    echo "==> Signing (ad-hoc; no certificate in the keychain)"
    codesign --force --sign - --identifier "$BUNDLE_ID" "$APP"
fi

# Nudge Finder and the Dock to pick up the new icon instead of a cached one.
touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "$APP" >/dev/null 2>&1 || true

if [ "$INSTALL" -eq 1 ]; then
    mkdir -p "$HOME/Applications"
    rm -rf "$HOME/Applications/$APP_NAME.app"
    cp -R "$APP" "$HOME/Applications/"
    echo "==> Installed to ~/Applications/$APP_NAME.app"
fi

echo "==> Done: $APP  (version $VERSION, built $BUILD_STAMP)"
